raw_data: test/true/online_retail_II.csv
clean_data: test/true/clean_data.csv
basket_data: test/true/basket.csv
product_dim: test/true/product_dim.csv
training_data: test/true/training_data.csv
test_data: test/true/test_data.csv
rec: test/true/rec.csv


apriori_args:
  min_support: 1
  use_colnames: True

get_recommendations_valid:
  association_rules_args:
    metric: lift
    min_threshold: 1
  ante_num_filter: 1 # filter recommendations where antecedents only have ante_num_filter products
  rank_arg:
    method: first
    ascending: False
  rank_filter: 2 # For each antecedents, keep rank_filter recommendations

get_recommendations_invalid:
  association_rules_args:
    metric: lift
    min_threshold: 1000
  ante_num_filter: 1 # filter recommendations where antecedents only have ante_num_filter products
  rank_arg:
    method: first
    ascending: False
  rank_filter: 2 # For each antecedents, keep rank_filter recommendations

frozenset2String_valid: antecedents
frozenset2String_invalid: confidence



